# Generated by Django 4.0.4 on 2022-04-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gametype',
            old_name='title',
            new_name='label',
        ),
    ]
